### ISSUE TITLE
Generator sometimes generate future dates

### ISSUE THREAD

**Issue by depryf** [imsweb/data-generator#11]
I think it was the date of last contact, but it could have been the DX one or the DOB one. Happens when no end-DX year param is set, forcing the generator to use the "current year".

**Comment by agsong** [comment]
@depryf Just letting you know that I have everything set up and working. Also, do I need the jar file for the SEER code style for Intellij?

**Comment by depryf** [comment]
Awesome. Please try to follow the SEER conventions, but for now you don't need to get the file for IntelliJ. We can work that out another time.

**Comment by agsong** [comment]
I fixed the problem (at least for DX date and DOLC) and added to the unit test to make sure that future dates are never created. It actually had to do with the min date becoming greater than the max date in the execute method (regardless of whether a max date was assigned). Should I push a new branch?

**Comment by depryf** [comment]
Yes please, push a new branch and make a pull request. Thanks.

**Comment by depryf** [comment]
The changes have been merged.
