### ISSUE TITLE
Illegal DX year range caused by birth year

### ISSUE THREAD

**Issue by ericIN** [imsweb/data-generator#2]
The allowable range for the random year of birth depends only on the current year. As a result, the birth year could be later than the max DX year defined in the options. When it's equal to or later than the max DX year, DateOfDiagnosisRule is updating the min DX year to be after max DX year. This results in an invalid range for the random number generator. 

I think DateOfDiagnosisRule is fine. BirthRule just needs to offset the min or max DX year, rather than the current year.

**Comment by depryf** [comment]
That makes sense. Please make sure to unit test this in the BirthRuleTest.

**Comment by depryf** [comment]
Fixed.
