### ISSUE TITLE
Birth state not being set correctly

### ISSUE THREAD

**Issue by ericIN** [imsweb/data-generator#3]
BirthRule is putting "XX" for all birth states. It's using the current address state if defined, and "XX" otherwise. It shouldn't use "XX" at all, but this is happening for all records because BirthRule is executing before AddressCurrentRule. Also getRequiredProperties() was not defined for BirthRule, which would have caught this.

I don't think this even needs the current address state. BirthRule can be changed to use the state defined in the options. I'm pretty sure AddressCurrentRule is doing that anyway. The dependency doesn't seem necessary.

**Comment by depryf** [comment]
Agreed. Please remove the dependency and just use the state from the option. I guess if no state is provided in the options, the birth state will be left blank...

**Comment by ctmay4** [comment]
It is possible that birth state could be assigned to another state from the default.  I guess we just don't care at this point?

**Comment by depryf** [comment]
True. We can improve later and do fancy stuff, but for now we need to keep those rules simple.

**Comment by ctmay4** [comment]
I would do something like 90% are from the same state and 10% are from a random other state.

**Comment by depryf** [comment]
We can do that, that's fine.
