### ISSUE TITLE
Optional Bad Data

### ISSUE THREAD

**Issue by halla-ims** [imsweb/data-generator#32]
I would "love" the optional selection of being able to generate random bad data. I envision this like so: A checkbox which lets you turn on bad data, and a percentage entry for how many records should get bad data. And then a popup checkbox list of enforcement rules you could turn off for a given run (used for bad data records). For example you could turn off: City is valid for State, Zipcode is valid for State, Date of Diagnosis is not blank, Birthdate is not blank, Only Valid Histologies, etc. It would just turn off requirements that are already in place when generating the data.

**Comment by depryf** [comment]
That sounds like a great idea. Not sure where that will fall with all the other requests of this (simple) project, but time will tell :-)

**Comment by depryf** [comment]
We have too many priorities and not enough time to process them.  I don't think this is every going to happen (it's also not simple to put in place). 

If this is needed by a project, feel free to make a Pull Request for the changes. 

I am closing this issue for now.
