### ISSUE TITLE
Clean up Sonarcloud findings

### ISSUE THREAD

**Issue by ctmay4** [imsweb/data-generator#43]
In #42 the build process was updated to build in Github Actions and to automatically run Sonarcloud. The README has a link to findings.

https://sonarcloud.io/summary/overall?id=imsweb_data-generator

There are some things that should be cleaned up:

1. Fix the 3 "bugs". They all deal with not properly closing a stream.
2. Clean up the 29 code smells.
3. Review the code duplication. For example, `FacilityDto` and `FacilityFrequencyDto` appear to be exactly the same. There are other as well.

**Comment by ctmay4** [comment]
@caij-ims no rush on this. Whenever you are light on work.

Adding @depryf so he can follow along.

**Comment by depryf** [comment]
@caij-ims I merged the other issue (the one that added random text).  I will wait for this one to be completed before releasing the library...

**Comment by caij-ims** [comment]
NaaccrDataGeneratorNaaccrDataRule is an unused abstract class with no inheritors. Can we delete it?

**Comment by depryf** [comment]
Yes.

**Comment by caij-ims** [comment]
Many of the fields in the DTOs are unused. Do we still want to keep them just in case?

**Comment by depryf** [comment]
It's tricky because some might be used by external programs. It's hard to tell. Can you give me a few examples?

**Comment by caij-ims** [comment]
PhysicianFrequencyDto
Used: npi, lastName, firstName, addressState
Unused: middleName, namePrefix, nameSuffix, credentials, addressFirstLine, addressSecondLine, addressCity, addressPostalCode, addressTelephone, specialty01-03

**Comment by caij-ims** [comment]
FacilityFrequencyDto is similar to Physician.

CityFrequencyDto doesn't use longitude/latitude.

**Comment by depryf** [comment]
Adding @ctmay4 

I am pretty sure those three generators were added to be used in SEER*DMS but we never used them. 

For now, go ahead and remove any fields that is not set by a rule. 

I will submit an issue in SEER*DMS to either use those or remove them from this library...

**Comment by depryf** [comment]
@caij-ims I just merged a pull request.  Can this issue be closed?

**Comment by caij-ims** [comment]
Yes
